### ISSUE TITLE
Navigation Issues

### ISSUE THREAD

**Issue by Rand-Random** [ShokoAnime/ShokoDocs#35]
Spelling Error: 
![image](https://user-images.githubusercontent.com/9868626/46141331-f0a1a680-c253-11e8-8f7a-9220c49a4775.png)

Text inconsistency:
![image](https://user-images.githubusercontent.com/9868626/46141787-40cd3880-c255-11e8-9b6e-d2abb9f803b8.png)

![image](https://user-images.githubusercontent.com/9868626/46141899-943f8680-c255-11e8-9a72-f0a0821586ad.png)

"Creating settings.json" is missing on the right navigation bar

![image](https://user-images.githubusercontent.com/9868626/46142042-f26c6980-c255-11e8-918a-541720f47910.png)

![image](https://user-images.githubusercontent.com/9868626/46142118-2c3d7000-c256-11e8-8778-7c5263d1bfcf.png)

The links below Shoko Desktop and Shoko On Plex don't work they only have the url 
https://docs.shokoanime.com/#

Navigating to https://docs.shokoanime.com/faq.html - removes the entry "Frequently Asked Questions" from the sidebar, I know it doesn't make much sense to have it there since we are already on that page, and clicking it just brings you to the same page - but still I would like it to stay. (Same goes for "Changelog")

Those are the only 2 that disappear, if I navigate to https://docs.shokoanime.com/server/install_windows.html the Entry Shoko Server -> Installing Shoko Server -> Shoko Server On Windows - doesn't disappear.

On FAQ the blog post for Anime Buddy gives a 404, https://shokoanime.com/anime-buddy-discontinued/

That's it for now.

**Comment by ElementalCrisis** [comment]
@Undeadhunter can you add the Linux mentions and spelling fixes to your PR. 

> The links below Shoko Desktop and Shoko On Plex don't work they only have the url

That's because they don't exist, yet. I need to write them.

> Navigating to https://docs.shokoanime.com/faq.html - removes the entry "Frequently Asked Questions" from the sidebar, I know it doesn't make much sense to have it there since we are already on that page, and clicking it just brings you to the same page - but still I would like it to stay. (Same goes for "Changelog")

Yeah I coded it that way, to me it seems kind of pointless to have a link to the FAQ or Changelog when you're on that page. The reason I didn't do that for the other links is to preserve link structure. @Undeadhunter, if you want to restore your previous idea https://github.com/ShokoAnime/ShokoDocs/blob/ae4cb2fd0aad87e558e294bf65c4d00a7fa8a9eb/_includes/_sidebar.html that would solve the issue. 

> On FAQ the blog post for Anime Buddy gives a 404, https://shokoanime.com/anime-buddy-discontinued/ 

Will fix on next update unless @Undeadhunter wants to add it to his PR, the correct link is https://shokoanime.com/blog/anime-buddy-discontinued/
