### ISSUE TITLE
Dark Theme is broken

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDocs#40]
![dar](https://user-images.githubusercontent.com/6052025/61620619-812cf580-ac71-11e9-8a65-ec1a92cd5f5b.png)

**Comment by alecmeelan** [comment]
Please see issue #38. It isn't broken, just incomplete. (I'm working on it, just waiting for a few changes from ElementalCrisis)

**Comment by ElementalCrisis** [comment]
Yeah I left it up to the community to decide on the color scheme.

**Comment by bigretromike** [comment]
If you advertised it as 'new feature' I assumed it was supposed to be working and is broken right now.

**Comment by bigretromike** [comment]
@Konack that #38 just looks like a template for community to make more color-themes, no to fix dark theme, saw that before, but thanks for link anyway

**Comment by alecmeelan** [comment]
@bigretromike Thats the general CSS. It isn't "broken" but not stylized fully. The file mentioned in #38 is what everything on https://docs.shokoanime.com/ references for the dark theme styling. He mentions that the community can decide on the coloring and that's exactly what that file is for. Regardless this is since been closed and I should finish it tonight.
